version: "3"
services:
  postgres:
    image: elestio/postgres:15
    container_name: postgres
    hostname: postgres
    restart: always
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --locale=C
    ports:
      - 172.17.0.1:52282:5432

  element:
    image: vectorim/element-web:${SOFTWARE_VERSION_TAG}
    container_name: element
    hostname: element
    restart: always
    ports:
      - "172.17.0.1:8080:80"
    volumes:
      - ./element-config.json:/app/config.json
      - ./matrix/federation.json:/usr/share/nginx/html/.well-known/matrix/server

  synapse:
    image: matrixdotorg/synapse:${SOFTWARE_VERSION_TAG}
    container_name: synapse
    hostname: synapse
    restart: always
    ports:
      - "172.17.0.1:8008:8008"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./synapse:/data

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:37620:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
